config/routes.rb
Sniphr::Application.routes.draw do

  resources :queries, :only => [:index]

  match "/sniphs/mine" => "sniphs#index", :as => :my_sniphs

  resources :sniphs, :only => [:index, :show, :destroy] do
    collection do
      get 'save'
    end
  end

  root :to => "static#index"
  match "/faq" => "static#faq", :as => :faq

  match "/auth/:provider/callback" => "sessions#create", :as => :signin
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/session_status" => "sessions#session_status"

  resources :users, :only => [:index, :edit, :update]
  match "/settings" => "users#edit", :as => :settings
  match "/chrome_options" => "users#chrome_options", :as => :chrome_options

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :sniphs
  has_many :queries

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
      
      case user.provider.to_sym
      when :twitter
        user.nickname = auth["info"]["nickname"]
        user.location = auth["info"]["location"]
        user.description = auth["info"]["description"]
      when :facebook
        user.nickname = auth["info"]["name"]
        user.description = auth["extra"]["user_hash"]["bio"]
        user.email = auth["info"]["email"]
        user.fb_url = auth["info"]["urls"]["Facebook"]
      end
      
    end
  end

  def public_mode?
    self.mode == 'public'
  end

  def manually_configured?
    self.created_at != self.updated_at
  end
  
  def facebook?
    self.provider == 'facebook'
  end
  
  def twitter?
    self.provider == 'twitter'
  end

  def url
    case self.provider.to_sym
    when :twitter then "https://twitter.com/#!/#{nickname}"
    when :facebook then fb_url.present? ? fb_url : "http://www.facebook.com/profile.php?id=#{uid}"
    end
  end
  
  def self.modes_collection
    {'Public' => 'public', 'Private' => 'private'}
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.includes(:sniphs)#.order('sniphs.created_at DESC')
  end
    
  def edit
    if !logged_in?
      redirect_to(root_path)
      return
    end
  end

  def chrome_options
    if params[:last_url].present?
      @current_url = params[:last_url]
      @domain = @current_url.domain_without_www
      @num_sniphs_at_url = Sniph.where("url LIKE ?", "%#{@current_url}%").count
      @num_sniphs_at_domain = Sniph.where("url LIKE ?", "%#{@domain}%").count
    end

    respond_to do |format|
      format.html
    end
  end

  def update
    respond_to do |format|
      if current_user.update_attributes(params[:user])
        format.html { redirect_to(root_path, :notice => 'Settings saved.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

end

app/views/users/_user.html.haml
.user
  = link_to image_tag(user.image, :class => "avatar"), user.url

  .meta
    %span.name= link_to(user.nickname, user.url)
    %span.location{:title => user.location}= truncate(user.location, :length => 17)

app/views/users/chrome_options.html.haml
%ul#chrome_options

  - if !logged_in?
    %li Your are signed out of Sniphr.com
    %li= link_to("Sign in with Twitter", "/auth/twitter", :target => "_blank")
    %li= link_to("Sign in with Facebook", "/auth/facebook", :target => "_blank")
    
  - elsif @current_url.blank?
    %li Sorry, there was a problem getting your current URL.

  - else
    %li
      %h1= truncate(@current_url.remove_http_and_www, :length => 60)

    - if @num_sniphs_at_url.zero?
      %li.weak= "No sniphs at this URL"
    - else
      %li= link_to("View the #{pluralize(@num_sniphs_at_url, 'sniph')} from this URL", "/sniphs?q=#{@current_url.remove_http_and_www}", :target => "_blank")
      
    - if @num_sniphs_at_domain.zero?
      %li.weak= "No sniphs at this domain"
    - else
      %li= link_to("View the #{pluralize(@num_sniphs_at_domain, 'sniph')} from this domain", "/sniphs?q=#{@domain}", :target => "_blank")


    %li.weak Highlight this URL's sniphs inline (soon)
    %li= link_to("Your sniphs", my_sniphs_path, :target => "_blank")
    %li= link_to("Settings", settings_path, :target => "_blank")
    %li= link_to("Sniphr.com", root_path, :target => "_blank")
    

app/views/users/edit.html.haml
%div.content

  %h1 Settings
  
  %p
    You are currently signed in using your 
    = link_to(current_user.nickname, current_user.url)
    = current_user.provider.titlecase
    account.

  = semantic_form_for(current_user, :html => {:class => ""}) do |form|
    = errors_for form
    
    = form.inputs do
      = form.input :mode, :as => :radio, :collection => User.modes_collection, :include_blank => false#, :hint => t('formtastic.hints.user.mode')

    = form.buttons do
      = form.submit "Save"

app/views/users/index.html.haml
%div.content

  %h1 Users

  %div.users
    = render :partial => "user", :collection => @users