config/routes.rb
Sniphr::Application.routes.draw do

  resources :queries, :only => [:index]

  match "/sniphs/mine" => "sniphs#index", :as => :my_sniphs

  resources :sniphs, :only => [:index, :show, :destroy] do
    collection do
      get 'save'
    end
  end

  root :to => "static#index"
  match "/faq" => "static#faq", :as => :faq

  match "/auth/:provider/callback" => "sessions#create", :as => :signin
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/session_status" => "sessions#session_status"

  resources :users, :only => [:index, :edit, :update]
  match "/settings" => "users#edit", :as => :settings
  match "/chrome_options" => "users#chrome_options", :as => :chrome_options

end

app/views/layouts/application.html.haml
<!DOCTYPE html> 
%html
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html; charset=utf-8'}
    = csrf_meta_tag # required for rails 3 js
    %title sniphr
    
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag "uniform.default"
    
    /[if IE]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    /[if lt IE 7]
      = stylesheet_link_tag 'compiled/ie6.css', :media => 'screen, projection'
    
    = javascript_include_tag "head.min"
    = headjs_include_tag configatron.javascripts
    
  %body
    
    - unless request.path == chrome_options_path
      #top_bar
        = logo
        = user_nav
    
    = yield
    
    - unless request.path == chrome_options_path
      #bottom_bar
        %ul
          %li
            Sniphr is a 
            = link_to("wordnik", "http://wordnik.com")
            experiment.